# IMPORTAMOS LIBRERIAS

In [1]:
# utilizado para manejos de directorios y rutas
import os

# Computacion vectorial y cientifica para python
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
# Librerias para graficación (trazado de gráficos)
from matplotlib import pyplot
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # Necesario para graficar superficies 3D
# llama a matplotlib a embeber graficas dentro de los cuadernillos
%matplotlib inline

In [3]:
#Cargamos el drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# CARGA DE DATOS
se procede a cargar los datos para su visualizacion

In [4]:
# Cargar datos
data = pd.read_csv('/content/drive/MyDrive/Data/london_merged.csv')
# Mostramos los tipos de datos que tenemos y otra
data.info()
#mostramos los primos 5 datos del dataset
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   timestamp     17414 non-null  object 
 1   cnt           17414 non-null  int64  
 2   t1            17414 non-null  float64
 3   t2            17414 non-null  float64
 4   hum           17414 non-null  float64
 5   wind_speed    17414 non-null  float64
 6   weather_code  17414 non-null  float64
 7   is_holiday    17414 non-null  float64
 8   is_weekend    17414 non-null  float64
 9   season        17414 non-null  float64
dtypes: float64(8), int64(1), object(1)
memory usage: 1.3+ MB


timestamp  cnt   t1   t2    hum  wind_speed  weather_code  \
0  2015-01-04 00:00:00  182  3.0  2.0   93.0         6.0           3.0   
1  2015-01-04 01:00:00  138  3.0  2.5   93.0         5.0           1.0   
2  2015-01-04 02:00:00  134  2.5  2.5   96.5         0.0           1.0   
3  2015-01-04 03:00:00   72  2.0  2.0  100.0         0.0           1.0   
4  2015-01-04 04:00:00   47  2.0  0.0   93.0         6.5           1.0   

   is_holiday  is_weekend  season  
0         0.0         1.0     3.0  
1         0.0         1.0     3.0  
2         0.0         1.0     3.0  
3         0.0         1.0     3.0  
4         0.0         1.0     3.0

# FUNCION PARA ENCONTRAR DATOS NULOS
Usando una funcion vemos si hay algun dato nulo e imprimos la posicion del dato

In [5]:
def tieneNull(data):
  filas, columnas = np.where(data.isnull())
  # Imprimir las posiciones de los valores nulos
  for fila, columna in zip(filas, columnas):
      print(f"Valor nulo encontrado en la posición ({fila}, {columna})")
tieneNull(data)
print("Número de valores faltantes en los datos:", data.isnull().sum().sum())

Número de valores faltantes en los datos: 0


# SEPARADO DE DATOS EN AÑO, MES, DIA Y HORA



In [6]:
# Vamos a convertir datos de tiempo al formato de fecha y hora para que podamos separar la fecha y la hora
data['timestamp'] = pd.to_datetime(data['timestamp'])

In [7]:
#Separate year, month, day, weekday, hour from timestamp
data["year"] =data['timestamp'].dt.year
data["month"] = data['timestamp'].dt.month
data["day_of_month"] = data['timestamp'].dt.day
data["hour"] = data['timestamp'].dt.hour
data.head()

timestamp  cnt   t1   t2    hum  wind_speed  weather_code  \
0 2015-01-04 00:00:00  182  3.0  2.0   93.0         6.0           3.0   
1 2015-01-04 01:00:00  138  3.0  2.5   93.0         5.0           1.0   
2 2015-01-04 02:00:00  134  2.5  2.5   96.5         0.0           1.0   
3 2015-01-04 03:00:00   72  2.0  2.0  100.0         0.0           1.0   
4 2015-01-04 04:00:00   47  2.0  0.0   93.0         6.5           1.0   

   is_holiday  is_weekend  season  year  month  day_of_month  hour  
0         0.0         1.0     3.0  2015      1             4     0  
1         0.0         1.0     3.0  2015      1             4     1  
2         0.0         1.0     3.0  2015      1             4     2  
3         0.0         1.0     3.0  2015      1             4     3  
4         0.0         1.0     3.0  2015      1             4     4

In [8]:
#convertir a tipo entero

data.weather_code = data.weather_code.astype(int)
data.season = data.season.astype(int)
data.is_weekend = data.is_weekend.astype(int)
data.is_holiday = data.is_holiday.astype(int)
#elimino la columna de tiempo
data.drop('timestamp', axis=1, inplace=True)
data.head()

cnt   t1   t2    hum  wind_speed  weather_code  is_holiday  is_weekend  \
0  182  3.0  2.0   93.0         6.0             3           0           1   
1  138  3.0  2.5   93.0         5.0             1           0           1   
2  134  2.5  2.5   96.5         0.0             1           0           1   
3   72  2.0  2.0  100.0         0.0             1           0           1   
4   47  2.0  0.0   93.0         6.5             1           0           1   

   season  year  month  day_of_month  hour  
0       3  2015      1             4     0  
1       3  2015      1             4     1  
2       3  2015      1             4     2  
3       3  2015      1             4     3  
4       3  2015      1             4     4

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17414 entries, 0 to 17413
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cnt           17414 non-null  int64  
 1   t1            17414 non-null  float64
 2   t2            17414 non-null  float64
 3   hum           17414 non-null  float64
 4   wind_speed    17414 non-null  float64
 5   weather_code  17414 non-null  int64  
 6   is_holiday    17414 non-null  int64  
 7   is_weekend    17414 non-null  int64  
 8   season        17414 non-null  int64  
 9   year          17414 non-null  int64  
 10  month         17414 non-null  int64  
 11  day_of_month  17414 non-null  int64  
 12  hour          17414 non-null  int64  
dtypes: float64(4), int64(9)
memory usage: 1.7 MB


# Asignamos los datos a las variables para su prediccion

In [83]:
#dato que queremos predecir
Y = data['cnt']
# Variables predictorias
X = data.drop('cnt', axis = 1)


In [84]:
X = X.to_numpy()
Y = Y.to_numpy()

# Separamos los datos entre datos de prueba y datos de predicion

In [19]:
#dividir el conjunto de datos
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 42)


In [20]:
m = Y.size
print(X.shape)
print(Y.shape)
print(X)
print('---'*20)
print(Y)

(17414, 12)
(17414,)
[[ 3.   2.  93.  ...  1.   4.   0. ]
 [ 3.   2.5 93.  ...  1.   4.   1. ]
 [ 2.5  2.5 96.5 ...  1.   4.   2. ]
 ...
 [ 5.5  1.5 78.5 ...  1.   3.  21. ]
 [ 5.5  1.5 76.  ...  1.   3.  22. ]
 [ 5.   1.  76.  ...  1.   3.  23. ]]
------------------------------------------------------------
[182 138 134 ... 337 224 139]


#Definimos las clases y funciones para la prediccion

In [11]:
def relu(x):
  return np.maximum(0, x)

def reluPrime(x):
  return x > 0

In [14]:
def linear(x):
    return x

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def softmax(x):
    return np.exp(x) / np.exp(x).sum(axis=-1,keepdims=True)

In [13]:
# Mean Square Error -> usada para regresión (con activación lineal)
def mse(y, y_hat):
    return np.mean((y_hat - y.reshape(y_hat.shape))**2)

# Binary Cross Entropy -> usada para clasificación binaria (con sigmoid)
def bce(y, y_hat):
    return - np.mean(y.reshape(y_hat.shape)*np.log(y_hat) - (1 - y.reshape(y_hat.shape))*np.log(1 - y_hat))

# Cross Entropy (aplica softmax + cross entropy de manera estable) -> usada para clasificación multiclase
def crossentropy(y, y_hat):
    logits = y_hat[np.arange(len(y_hat)),y]
    entropy = - logits + np.log(np.sum(np.exp(y_hat),axis=-1))
    return entropy.mean()

In [15]:
def grad_mse(y, y_hat):
    return y_hat - y.reshape(y_hat.shape)

def grad_bce(y, y_hat):
    return y_hat - y.reshape(y_hat.shape)

def grad_crossentropy(y, y_hat):
    answers = np.zeros_like(y_hat)
    answers[np.arange(len(y_hat)),y] = 1
    return (- answers + softmax(y_hat)) / y_hat.shape[0]

In [12]:
# clase base MLP

class MLP():
  def __init__(self, D_in, H, D_out, loss, grad_loss, activation):
    # pesos de la capa 1
    self.w1, self.b1 = np.random.normal(loc=0.0,
                                  scale=np.sqrt(2/(D_in+H)),
                                  size=(D_in, H)), np.zeros(H)
    # pesos de la capa 2
    self.w2, self.b2 = np.random.normal(loc=0.0,
                                  scale=np.sqrt(2/(H+D_out)),
                                  size=(H, D_out)), np.zeros(D_out)
    self.ws = []
    # función de pérdida y derivada
    self.loss = loss
    self.grad_loss = grad_loss
    # función de activación
    self.activation = activation

  def __call__(self, x):
    # salida de la capa 1
    self.h_pre = np.dot(x, self.w1) + self.b1
    self.h = relu(self.h_pre)
    # salida del MLP
    y_hat = np.dot(self.h, self.w2) + self.b2
    return self.activation(y_hat)

  def fit(self, X, Y, epochs = 100, lr = 0.001, batch_size=None, verbose=True, log_each=1):
    batch_size = len(X) if batch_size == None else batch_size
    batches = len(X) // batch_size
    l = []
    for e in range(1,epochs+1):
        # Mini-Batch Gradient Descent
        _l = []
        for b in range(batches):
            # batch de datos
            x = X[b*batch_size:(b+1)*batch_size]
            y = Y[b*batch_size:(b+1)*batch_size]
            # salida del perceptrón
            y_pred = self(x)
            # función de pérdida
            loss = self.loss(y, y_pred)
            _l.append(loss)
            # Backprop
            dldy = self.grad_loss(y, y_pred)
            grad_w2 = np.dot(self.h.T, dldy)
            grad_b2 = dldy.mean(axis=0)
            dldh = np.dot(dldy, self.w2.T)*reluPrime(self.h_pre)
            grad_w1 = np.dot(x.T, dldh)
            grad_b1 = dldh.mean(axis=0)
            # Update (GD)
            self.w1 = self.w1 - lr * grad_w1
            self.b1 = self.b1 - lr * grad_b1
            self.w2 = self.w2 - lr * grad_w2
            self.b2 = self.b2 - lr * grad_b2
        l.append(np.mean(_l))
        # guardamos pesos intermedios para visualización
        self.ws.append((
            self.w1.copy(),
            self.b1.copy(),
            self.w2.copy(),
            self.b2.copy()
        ))
        if verbose and not e % log_each:
            print(f'Epoch: {e}/{epochs}, Loss: {np.mean(l):.5f}')

  def predict(self, ws, x):
    w1, b1, w2, b2 = ws
    h = relu(np.dot(x, w1) + b1)
    y_hat = np.dot(h, w2) + b2
    return self.activation(y_hat)

In [16]:
# MLP para regresión
class MLPRegression(MLP):
    def __init__(self, D_in, H, D_out):
        super().__init__(D_in, H, D_out, mse, grad_mse, linear)

# MLP para clasificación binaria
class MLPBinaryClassification(MLP):
    def __init__(self, D_in, H, D_out):
        super().__init__(D_in, H, D_out, bce, grad_bce, sigmoid)

# MLP para clasificación multiclase
class MLPClassification(MLP):
    def __init__(self, D_in, H, D_out):
        super().__init__(D_in, H, D_out, crossentropy, grad_crossentropy, linear)

# Entrenamos al modelo

In [67]:
model = MLPRegression(D_in=12, H=1200, D_out=1)
epochs, lr = 500, 0.01

# normalización datos
x_mean = np.mean(x_train)
x_std = np.std(x_train)
x_std = np.nan_to_num(x_std, nan=1.0)


# Calcula x_norm
x_norm = (x_train - x_mean) / x_std

model.fit(x_norm, y_train, epochs, lr, batch_size=1, log_each=10)

Epoch: 10/500, Loss: 1381168.42151
Epoch: 20/500, Loss: 1279575.45498
Epoch: 30/500, Loss: 1245711.13280
Epoch: 40/500, Loss: 1228778.97172
Epoch: 50/500, Loss: 1218619.67506
Epoch: 60/500, Loss: 1211846.81063
Epoch: 70/500, Loss: 1207009.05032
Epoch: 80/500, Loss: 1203380.73008
Epoch: 90/500, Loss: 1200558.70324
Epoch: 100/500, Loss: 1198301.08176
Epoch: 110/500, Loss: 1196453.93691
Epoch: 120/500, Loss: 1194914.64954
Epoch: 130/500, Loss: 1193612.17561
Epoch: 140/500, Loss: 1192495.76938
Epoch: 150/500, Loss: 1191528.21732
Epoch: 160/500, Loss: 1190681.60927
Epoch: 170/500, Loss: 1189934.60216
Epoch: 180/500, Loss: 1189270.59584
Epoch: 190/500, Loss: 1188676.48493
Epoch: 200/500, Loss: 1188141.78510
Epoch: 210/500, Loss: 1187658.00907
Epoch: 220/500, Loss: 1187218.21268
Epoch: 230/500, Loss: 1186816.65945
Epoch: 240/500, Loss: 1186448.56900
Epoch: 250/500, Loss: 1186109.92577
Epoch: 260/500, Loss: 1185797.33203
Epoch: 270/500, Loss: 1185507.89338
Epoch: 280/500, Loss: 1185239.12892
E

# Calculamos los pesos

In [68]:
# últimos pesos encontrados

w = model.ws[-1]
w

(array([[ 2.41390511, -0.02364074,  0.10611969, ...,  0.05890811,
          0.07168861,  1.88248132],
        [ 2.39438689, -0.07638876,  0.1652482 , ...,  0.05583413,
          0.07534668,  1.92052861],
        [ 1.72509235,  0.00976826,  0.10801723, ..., -0.00456898,
          0.03860555,  1.44786406],
        ...,
        [ 2.58081081,  0.01438127,  0.12171396, ...,  0.02198754,
          0.0710796 ,  2.14995966],
        [ 2.51455086,  0.04386143,  0.12355166, ..., -0.00283026,
          0.06248328,  2.16316327],
        [ 2.31136374,  0.03363228,  0.13216549, ..., -0.01237236,
          0.04328094,  1.93573316]]),
 array([-8.1162611 ,  0.        , -0.48584375, ...,  0.        ,
        -0.23782186, -6.64301118]),
 array([[-1.11082474e+01],
        [ 1.35402736e-02],
        [ 1.15961267e+00],
        ...,
        [ 1.00204254e-02],
        [ 2.47574491e-01],
        [-1.31184681e+01]]),
 array([1181.36301495]))

In [69]:
print("Primeros 5 datos de entrada de prueba (X_test):")
print(x_test[:5])

print("Primeras 5 etiquetas de prueba (y_test):")
print(y_test[:5])

Primeros 5 datos de entrada de prueba (X_test):
[[1.400e+01 1.400e+01 8.500e+01 6.000e+00 2.000e+00 0.000e+00 0.000e+00
  1.000e+00 2.016e+03 8.000e+00 1.700e+01 4.000e+00]
 [7.000e+00 6.000e+00 8.700e+01 7.000e+00 3.000e+00 0.000e+00 0.000e+00
  0.000e+00 2.016e+03 4.000e+00 8.000e+00 7.000e+00]
 [1.600e+01 1.600e+01 7.700e+01 2.500e+01 3.000e+00 0.000e+00 0.000e+00
  2.000e+00 2.015e+03 1.100e+01 1.000e+01 0.000e+00]
 [1.800e+01 1.800e+01 5.400e+01 2.100e+01 2.000e+00 0.000e+00 1.000e+00
  2.000e+00 2.015e+03 9.000e+00 2.700e+01 1.500e+01]
 [1.350e+01 1.350e+01 7.700e+01 1.400e+01 7.000e+00 0.000e+00 1.000e+00
  2.000e+00 2.015e+03 1.000e+01 1.800e+01 1.700e+01]]
Primeras 5 etiquetas de prueba (y_test):
[  66 1749  172 2866 1550]


# Realizamos laprediccion

In [108]:
# nuevo punto
#x_new = x_test
#X_new =x_test[5103:5104]
#1:t1 , 2:t2 ,3:hum , 4:wind_speed  , 5:weather_code, 6:is_holiday
#  7:is_weekend ,8:season , 9:year   , 10:month ,  11.day_of_month , 12;hour
X_new = [3.0,	2.0,	100.0,	5.0,	3,	0,	1,	3,	2019,	1,	25,	20]
y_pred = model.predict(w, X_new)

print(f"La cantidad de bicicletas que se alquilara ese dia son:{y_pred[0].round()}")

La cantidad de bicicletas que se alquilara ese dia son:1255.0
